version: '3.8'
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ../:/workspace
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
